[program:rsyslog]
command=/usr/sbin/rsyslogd -n -iNONE
autorestart=true
priority=10

[program:cron]
command=/usr/sbin/cron -f
autorestart=true
priority=10

[program:php-fpm]
command=/usr/sbin/php-fpm8.1 -F
autorestart=true
priority=20

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=30
